# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nWii0UtBOwsOiKHcZzkjR_XTHwBwS4yp
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install torch==1.13.0+cu116 torchvision==0.14.0+cu116 torchaudio==0.13.0 torchtext==0.14.0 --extra-index-url https://download.pytorch.org/whl/cu116

import os
if os.path.isfile("train_dreambooth.py"):
    os.unlink("train_dreambooth.py")
if os.path.isfile("convert_diffusers_to_original_stable_diffusion.py"):
    os.unlink("convert_diffusers_to_original_stable_diffusion.py")

#!wget -q https://github.com/ShivamShrirao/diffusers/raw/main/examples/dreambooth/train_dreambooth.py
!wget -q https://github.com/ethan-team/diffusers_colab/raw/main/examples/dreambooth/train_dreambooth.py
!wget -q https://github.com/ShivamShrirao/diffusers/raw/main/scripts/convert_diffusers_to_original_stable_diffusion.py

# %pip install git+https://github.com/ShivamShrirao/diffusers
# %pip install -U --pre triton
# %pip install accelerate==0.12.0 transformers ftfy bitsandbytes 
# %pip install gradio natsort

# %pip install https://github.com/brian6091/xformers-wheels/releases/download/0.0.15.dev0%2B4c06c79/xformers-0.0.15.dev0+4c06c79.d20221205-cp38-cp38-linux_x86_64.whl
# %pip install safetensors